name: xai
channels:
  - defaults
  - pytorch
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  # Core environment
  - python=3.8.19
  - conda-forge::simpleitk
  - conda-forge::pycocotools
  - notebook
  - requests
  - scikit-image
  - scikit-learn
  - openpyxl
  - pytorch::pytorch=1.12.1
  - pytorch::torchvision=0.13.1
  - pytorch::captum

  - pip
  # Pinned packages from cheXlocalize
  - pip:
    - cycler==0.10.0
    - fonttools==4.33.3
    - kiwisolver==1.2.0
    - matplotlib==3.1.3
    - numpy==1.18.1
    - opencv-python==4.3.0.38
    - packaging==21.3
    - pandas==1.2.1
    - Pillow==7.1.2
    # - pycocotools==2.0.8
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - scipy==1.7.3
    - seaborn==0.10.1
    - six==1.15.0
    - statsmodels==0.13.2
    - tqdm==4.64.0
    - typing-extensions==3.7.4.3

